### ISSUE TITLE
Create a healthcheck to monitor the balance of the claim-account

### ISSUE THREAD

**Issue by Qkyrie** [FundRequest/Azrael#3]
The account that will submit the claims needs to be monitored when it comes to balance.

Create a health endpoint that will be "NOK" if the balance < 1 eth

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/29/badge)](https://dev-web.fundrequest.io/requests/29) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #3`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
